services:
  - type: web
    name: portfolio          # you can change this to your service name
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn --pythonpath portfolio portfolio.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true   # Render will auto-generate one if not provided
      - key: DEBUG
        value: False
      - key: EMAIL_HOST_PASSWORD
        value: bdjb aive ljgv mzvj
      - key: EMAIL_HOST_USER
        value: souranilbasak@gmail.com
